{% set name = "python-socks" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-socks-{{ version }}.tar.gz
  sha256: 96c096c46470a52f088ff1a6227a5141116955c9081080b06d4462391467713f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6.2
  run:
    - python >=3.6.2

test:
  imports:
    - python_socks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/romis2012/python-socks
  summary: Core proxy (SOCKS4, SOCKS5, HTTP tunneling) functionality for Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
