{% set name = "python-socks" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e0e86854805cb8c35b06bfdc027790a48b73f918288568731026b799eb45cfe8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - python_socks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/romis2012/python-socks
  summary: Core proxy (SOCKS4, SOCKS5, HTTP tunneling) functionality for Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
