{% set name = "python-socks" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cc4ad990d67bd238e496afefe436af0247793bbe01d1d4a0d37a3b124ff0baa3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - python_socks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/romis2012/python-socks
  summary: Core proxy (SOCKS4, SOCKS5, HTTP tunneling) functionality for Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
