{% set name = "python-socks" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1a5220d159f88a92ef2f77d1acb77d175d40cb34af9176609d3cf728cb7499c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - python_socks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/romis2012/python-socks
  summary: Core proxy (SOCKS4, SOCKS5, HTTP tunneling) functionality for Python
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
